server:
  port: 8091
  tomcat:
    max-threads: 1000
    max-connections: 1000
    accept-count: 80
    min-spare-threads: 10
    uri-encoding: utf-8
  servlet:
    context-path: /7979
spring:
  application:
    name: OnlineBankSystemApplication
  datasource:
     druid: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/dev_banksystem?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
     username: admin
     password: admin123
     type: com.zaxxer.hikari.HikariDataSource
     hikari:
       maximum-pool-size: 15
       minimum-idle: 5
       idle-timeout: 30000
  thymeleaf:
    cache: false
  #redis
  redis:
    database: 11
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.itcode.onlineSystem.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
